export const genres = [
    {
        id:'all',
        title:'all'
    },
    {
        id:'action',
        title:'action'
    },
    {
        id:'adult',
        title:'adult'
    },
    {
        id:'adventure',
        title:'adventure'
    },
    {
        id:'comedy',
        title:'comedy'
    },
    {
        id:'doujinshi',
        title:'doujinshi'   
    },
    {
        id:'drama',
        title:'drama'
    },
    {
        id:'ecchi',
        title:'ecchi'
    },
    {
        id:'fantasy',
        title:'fantasy'
    },
    {
        id:'gender-bender',
        title:'gender bender'
    },
    {
        id:'harem',
        title:'harem'
    },
    {
        id:'historical',
        title:'historical'
    },
    {
        id:'horror',
        title:'horror'
    },
    {
        id:'josei',
        title:'josei'
    },
    {
        id:'martial-arts',
        title:'martial arts'
    },
    {
        id:'mature',
        title:'mature'
    },
    {
        id:'mecha',
        title:'mecha'
    },
    {
        id:'mystery',
        title:'mystery'
    },
    {
        id:'one-shot',
        title:'one shot'
    },
    {
        id:'psychological',
        title:'psychological'
    },
    {
        id:'romance',
        title:'romance'
    },
    {
        id:'school-life',
        title:'school life'
    },
    {
        id:'sci-fi',
        title:'sci-fi'
    },
    {
        id:'sejnen',
        title:'sejnen'
    },
    {
        id:'shoujo',
        title:'shoujo'
    },
    {
        id:'shoujo-ai',
        title:'shoujo ai'
    },
    {
        id:'shounen',
        title:'shounen'
    },
    {
        id:'shounen-ai',
        title:'shounen ai'
    },
    {
        id:'slice-of-life',
        title:'slide of life'
    },
    {
        id:'smut',
        title:'smut'
    },
    {
        id:'sports',
        title:'sports'
    },
    {
        id:'supernatural',
        title:'supernatural'
    },
    {
        id:'tragedy',
        title:'tragedy'
    },
    {
        id:'webtoons',
        title:'webtoons'
    },
    {
        id:'yaoi',
        title:'yaoi'
    },
    {
        id:'yuri',
        title:'yuri'
    }
]